### PR TITLE
implemented bag-of-words based text classification with Maxent model

### PR DESCRIPTION
**Pull request by behrica**

### CODE REVIEW

**Review by cnuernber — CHANGES_REQUESTED** [review]
I reviewed this and overall it looks really good.

I would like:
1.  A simple unit test that allows us to know if the system is functional or was broken by e.g. an update to smile.  I don't care if it trains successfully but we should have at least quick and dirty one end-to-end test.
2. Logging long running ops is a good idea but it isn't clear to me where this logs to or how to control the logging.  Smile also logs quite a bit of information which is good and bad into the debug or trace logging channel; Given that pppmap has no dependency on clojure.tools.logging it appears this logs to stdout; if we are going to log things they need to log to the normal logging channels; either with a clojure.tools.logging or using log4j-api.  Note that neither of these pull in a concrete logging class themselves; they just use an API to log.

**Comment by behrica** [comment]
Both is addressed in last commit.

**Comment by behrica** [comment]
Please wait a bit before going ahead.
I will add as well the Maxent/binomial variant

**Comment by cnuernber** [comment]
Very cool.  Gogogo!

**Comment by behrica** [comment]
Binomial variant added.
You can go ahead with review.

**Comment by cnuernber** [comment]
Great work, tests pass and things appear solid.  

We should perhaps document this a bit but that can wait.

**Comment by behrica** [comment]
I plan to document it here :
https://github.com/scicloj/scicloj-data-science-handbook

I want to do one chapter of the handbook in Clojure:
https://jakevdp.github.io/PythonDataScienceHandbook/05.05-naive-bayes.html

In the python book they use Naive Bayes, instead of Maxent.
I will have a look at the Smile support for Naive Bayes.
http://haifengl.github.io/api/java/smile/classification/DiscreteNaiveBayes.html

I just saw, that it supports as well sparse data, which I had not seen before.
So I will probably make  Naive Bayes woking in tech.ml as well, in an other PR

**Pull request merged**
